trigger: none 
  # batch: 'true'
  # branches:
  #   include: [ dev ]
  # tags:
  #   exclude: [ NoBuild ]

variables:
  ORG:        PE
  APP :       AKS
  
  PREFIX:     AEU2
  ENV:        P0
  
  ADOProject: ADO_BRW
  PREFIXPRIMARY: AEU2
  APPPRIMARY: AKS
  UAI: 0

stages:
- stage: Deploy_All_${{ variables.PREFIX }}_${{ variables.ORG }}_${{ variables.APP }}_RG_${{ variables.ENV }}
  jobs:
  - template: ..\..\..\.ado\ado-pipelines-ALL.yml
    parameters:
      ORG:        ${{ variables.ORG }}
      APP :       ${{ variables.APP }}
      APPPRIMARY: ${{ variables.APPPRIMARY}}
      PREFIX:     ${{ variables.PREFIX }}
      ENV:        ${{ variables.ENV }}
      SP:         ${{ variables.ADOProject }}_${{ variables.PREFIX }}-${{ variables.ORG }}-${{ variables.APP }}-RG
      SPG0:       ${{ variables.ADOProject }}_${{ variables.PREFIXPRIMARY }}-${{ variables.ORG }}-${{ variables.APPPRIMARY }}-RG
      UAI:        ${{ variables.UAI }}