name: Bicep Bug Report
description: Create a report to help us improve
# title: "[Bug]: "
labels: ["Needs: Triage 🔍"]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        - It is recommended to reproduce this issue with the latest version of Bicep
        - Please search for existing issues and add comments there if relevant
        - If this is a feature request, please use the feature request template
        - If this is not related to a bug or you need further information or investigation, consider opening a discussion

  # - type: input
  #   id: contact
  #   attributes:
  #     label: Contact Details
  #     description: How can we get in touch with you if we need more info?
  #     placeholder: ex. email@example.com
  #   validations:
  #     required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is vs what you expected to happen
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Bicep version
      description: What version of our software are you running?
      render: PowerShell
      placeholder: |
        # Bicep CLI
        bicep --version

        # AZ CLI
        az bicep version

        # VS code by navigating to the extensions tab and searching for Bicep
        # or executing below and providing version for "ms-azuretools.vscode-bicep"
        code --list-extensions --show-versions --category azure

      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: What component is this related to
      description: If this is related to a certain component, please provide details
      options:
        - label: Bicep Language
        - label: Bicep.exe
        - label: AZ CLI
        - label: VSCode Extension
        - label: Linting
          required: false
  - type: textarea
    id: code-snippet
    attributes:
      label: Your sample Bicep code
      description: Please provide your Bicep code snippet below, this will automatically be formatted, no need for ```tagging```
      render: Bicep
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        - It is recommended to reproduce this issue with the latest version of Bicep
        - Please search for existing issues and add comments there if relevant
        - If this is a feature request, please use the feature request template
        - If this is not related to a bug or you need further information or investigation, consider opening a discussion
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/brwilkinson/AzureDeploymentFramework/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true