trigger: #none 
  batch: 'true'
  branches:
    include: [ dev ]
  tags:
    exclude: [ NoBuild ]

variables:
  ORG:        BRW
  PREFIX:     ACU1
  APP :       AOA
  ENV:        T5
  ADOProject: ADO_ADF

stages:
- stage: Deploy_All_${{ variables.PREFIX }}_${{ variables.ORG }}_${{ variables.APP }}_RG_${{ variables.ENV }}
  jobs:
  - template: ..\..\..\.ado\azure-pipelines-ALL.yml
    parameters:
      ORG:    ${{ variables.ORG }}
      PREFIX: ${{ variables.PREFIX }}
      APP :   ${{ variables.APP }}
      ENV:    ${{ variables.ENV }}
      SP:     ${{ variables.ADOProject }}_${{ variables.PREFIX }}-${{ variables.ORG }}-${{ variables.APP }}-RG