trigger: #none 
  batch: 'true'
  branches:
    include: [ dev ]
  tags:
    exclude: [ NoBuild ]

variables:
  ORG:    BRW
  PREFIX: ACU1
  APP :   AOA
  ENV:    T5

stages:
- stage: Subscription
  jobs:
  - template: ..\..\..\.ado\azure-pipelines-ALL.yml
    parameters:
      ORG:    $(ORG)
      PREFIX: $(PREFIX)
      APP :   $(APP)
      ENV:    $(ENV)