trigger: #none 
  batch: 'true'
  branches:
    include: [ dev ]
  tags:
    exclude: [ NoBuild ]

parameters:
- name: ORG
  displayName: ORG Code
  type: string
  default: BRW
  values:
  - BRW

- name: PREFIX
  displayName: Region Prefix
  type: string
  default: ACU1
  values:
  - ACU1
  - AEU2
  - AEU1
  - AWU2

- name: APP
  displayName: App/Tenant Name
  type: string
  default: AOA
  values:
  - AOA
  - ABC
  - ADF
  - HAA
  - HUB

- name: ENV
  displayName: Environment Name
  type: string
  default: T5

variables:
  ADOProject: ADF
  SP:         ADO_${{ variables.ADOProject }}_${{ variables.PREFIX }}-${{ variables.ORG }}-${{ variables.APP }}-RG


stages:
- stage: Subscription
  jobs:
  - job: Subscription_RG_RBAC
    pool:
      vmImage: windows-latest
      
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: ${{ variables.SP }}-G0
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/BicepDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "00-dp-sub-InitialRG" -SubscriptionDeploy'
        FailOnStandardError: true
        # azurePowerShellVersion: 'LatestVersion'
        preferredAzurePowerShellVersion: 6.0.0
        pwsh: true

- stage: RG_ALL
  jobs:
  - job: RG_ALL

    pool:
      vmImage: windows-latest
      # pool: AZC1-S1-Infra
      
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: ${{ variables.SP }}-${{ variables.ENV }}
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/BicepDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "01-dp-rg-ALLRG"'
        FailOnStandardError: true
        # azurePowerShellVersion: 'LatestVersion'
        preferredAzurePowerShellVersion: 6.0.0
        pwsh: true
        